// Api-Projects/react/my-todo-list/src/App.js
// App.js
import React, { useState } from 'react';
import AddTodo from './components/AddTodo';
import TodoList from './components/TodoList';

function App() {
  const [todos, setTodos] = useState([]);

  const addTodo = (task) => {
    setTodos([...todos, { id: Date.now(), task, completed: false }]);
  };

  const toggleComplete = (id) => {
    setTodos(todos.map(todo => {
      if (todo.id === id) {
        return { ...todo, completed: !todo.completed };
      }
      return todo;
    }));
  };

  const deleteTodo = (id) => {
    setTodos(todos.filter(todo => todo.id !== id));
  };

  return (
    <div className="container mx-auto p-4 w-1/2">
      <h1 className="text-2xl font-bold text-center mb-4">Todo List</h1>
      <AddTodo onAddTodo={addTodo} />
      <TodoList 
        todos={todos} 
        onToggleComplete={toggleComplete} 
        onDeleteTodo={deleteTodo} 
      />
    </div>
  );
}

export default App;

// Vue-Projects/vue/todo-list-app/src/App.vue
<template>
  <div class="min-h-screen bg-gray-100 flex flex-row items-center justify-center pt-16">
    <div class="w-full max-w-4xl mx-auto p-5">
      <h1 class="text-xl font-bold text-center mb-6">Vue Todos</h1>
      <todo-list></todo-list>
    </div>
  </div>
</template>

<script>
import TodoList from './components/TodoList.vue';

export default {
  name: 'App',
  components: {
    TodoList,
  }
};
</script>
