// react-projects/react/10.todo-list/src/App.js
import React from 'react';
import TodoList from './components/TodoList';
import './App.css';

function App() {
  return (
    <div className="App container mx-auto mt-10">
      <h1 className="text-2xl font-bold text-center mb-4">To-Do List</h1>
      <TodoList />
    </div>
  );
}

export default App;

// Vue-Projects/vue/todo-list-app/src/App.vue
<template>
  <div class="min-h-screen bg-gray-100 flex flex-row items-center justify-center pt-16">
    <div class="w-full max-w-4xl mx-auto p-5">
      <h1 class="text-xl font-bold text-center mb-6">Vue Todos</h1>
      <todo-list></todo-list>
    </div>
  </div>
</template>

<script>
import TodoList from './components/TodoList.vue';

export default {
  name: 'App',
  components: {
    TodoList,
  }
};
</script>
