// Vue-Projects/todo-list-app/src/components/AddTodo.vue
<template>
    <form @submit.prevent="addTodo" class="flex justify-center my-12">
      <input type="text" v-model="title" placeholder="Add a new todo..."
             class="rounded-l-lg p-4 border-t mr-0 border-b border-l text-gray-800 border-gray-200 bg-white w-96" />
      <button type="submit"
              class="px-8 rounded-r-lg bg-green-500 text-gray-800 font-bold p-4 uppercase border-green-500 border-t border-b border-r">Add</button>
    </form>
  </template>
  
  <script>
  export default {
    data() {
      return {
        title: ''
      };
    },
    methods: {
      addTodo() {
        if (this.title.trim()) {
          this.$store.dispatch('todos/addTodo', this.title.trim());
          this.title = '';
        }
      }
    }
  };
  </script>

// Api-Projects/react/my-todo-list/src/components/AddTodo.jsx
import React, { useState } from 'react';

function AddTodo({ onAddTodo }) {
  const [task, setTask] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    if (task.trim() === '') return;
    onAddTodo(task);
    setTask('');
  };

  return (
    <form onSubmit={handleSubmit} className="mb-4">
      <input
        type="text"
        value={task}
        onChange={(e) => setTask(e.target.value)}
        className="border border-gray-300 p-2 rounded-l-md"
        placeholder="Add a new task"
      />
      <button 
        type="submit" 
        className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r-md"
      >
        Add
      </button>
    </form>
  );
}

export default AddTodo;
