// Vue-Projects/vue/todo-list-app/src/components/TodoItem.vue
<template>
        <div class="bg-white p-4 rounded-lg shadow-md flex items-center justify-between">
        <span :class="{ 'line-through': todo.completed }" class="flex-1">
            {{ todo.title }}
        </span>
        <button @click="deleteTodo" class="text-red-500 hover:text-red-600">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
        </button>
        </div>
  </template>
  
  <script>
  export default {
    props: ['todo'],
    methods: {
      deleteTodo() {
        this.$store.dispatch('todos/deleteTodo', this.todo.id);
      },
    },
  };
  </script>

// Api-Projects/react/my-todo-list/src/components/TodoItem.jsx
import React from 'react';

function TodoItem({ todo, onToggleComplete, onDeleteTodo }) {
  return (
    <li 
      className={`flex items-center justify-between my-2 p-2 border ${todo.completed ? 'bg-green-100' : 'bg-white'}`}
    >
      <span className={`${todo.completed ? 'line-through' : ''}`}>
        {todo.task}
      </span>
      <div>
        <button 
          onClick={() => onToggleComplete(todo.id)}
          className="text-sm bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-2 rounded-l-md mr-1"
        >
          {todo.completed ? 'Undo' : 'Complete'}
        </button>
        <button 
          onClick={() => onDeleteTodo(todo.id)}
          className="text-sm bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-2 rounded-r-md"
        >
          Delete
        </button>
      </div>
    </li>
  );
}

export default TodoItem;
