// Vue-Projects/vue/todo-list-app/src/App.vue
<template>
  <div class="min-h-screen bg-gray-100 flex flex-row items-center justify-center pt-16">
    <div class="w-full max-w-4xl mx-auto p-5">
      <h1 class="text-xl font-bold text-center mb-6">Vue Todos</h1>
      <todo-list></todo-list>
    </div>
  </div>
</template>

<script>
import TodoList from './components/TodoList.vue';

export default {
  name: 'App',
  components: {
    TodoList,
  }
};
</script>

// React-Projects/react/04.timer-stopwatch/src/App.js
import React from 'react';
import TimerDisplay from './components/TimerDisplay';
import TimerControls from './components/TimerControls';
import useTimer from './hooks/useTimer';

function App() {
  const { time, isRunning, startTimer, stopTimer, resetTimer } = useTimer();

  return (
    <div className="flex justify-center items-center h-screen bg-gray-100">
      <div className="text-center">
        <TimerDisplay time={time} />
        <TimerControls
          isRunning={isRunning}
          startTimer={startTimer}
          stopTimer={stopTimer}
          resetTimer={resetTimer}
        />
      </div>
    </div>
  );
}

export default App;
